### ISSUE TITLE
I can not install Sambada in R

### ISSUE THREAD

**Issue by marifasa** [Sylvie/sambada#16]
Dear Sylvie, I can´t install Sambada in R. When I try to install, the message is: 
Warning in install.packages :
  cannot open compressed file 'sambada-0.8.1-windows/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection

Could you help me please?
Thanks! 
Mariana

**Comment by Sylvie** [comment]
Dear Mariana,

Thanks a lot for your interest in Sambada and RSambada!

Since you mention installing Sambada in R, I assume you want to install RSambada.
Unfortunately I can only provide limited advise on this topic: @SolangeD is the author of RSambada (https://github.com/SolangeD/R.SamBada), so she would likely have better clues.

Which steps did you take to install RSambada?
I could install RSambada and download Sambada with this process:
(using R 3.5.1 64bits on Windows 10)

`install.packages('devtools')`
`require('devtools')`
`if (!requireNamespace("BiocManager", quietly = TRUE))`
    `    install.packages("BiocManager")`
`BiocManager::install("SNPRelate")`
`remotes::install_github("SolangeD/RSambada")`
`downloadSambada()`

Does this work for you?

Kind regards,
Sylvie

**Comment by Sylvie** [comment]
Dear Mariana,

I hope that your issue is solved.
Feel free to reopen the ticket if the issue persists.

Kind regards,
Sylvie
